[package]
name = "canvaspads"
version = "0.1.0"
edition = "2021"

[dependencies]
raw-window-handle = { workspace = true }
wgpu = "23"

[dependencies.web-sys]
version = "0.3"
features = ["HtmlCanvasElement"]
