[package]
name = "canvaspads"
version = "0.1.0"
edition = "2021"

[dependencies]
raw-window-handle = { workspace = true }
wgpu = { version = "23", features = ["webgl"] }

[dependencies.web-sys]
version = "0.3"
features = ["HtmlCanvasElement"]
